version: "3.9"

services:
  call_center-web:
    build: ./web
    ports:
      - "${PORT_WEB}:${PORT_WEB}"
    env_file:
      - .env
    volumes:
      - ./jsoncred.json:/app/jsoncred.json

  call_center-agent:
    build: ./agent
    ports:
      - "${PORT_AGENT}:${PORT_AGENT}"
    env_file:
      - .env
    volumes:
      - ./jsoncred.json:/app/jsoncred.json
    enviroment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
