# docker-compose.yml
version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "${PORT_WEB}:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  agent:
    build:
      context: .
      dockerfile: voice_chat/agent/Dockerfile
    ports:
      - "${PORT_AGENT}:8081"
    env_file:
      - .env
    volumes:
      - .:/app