version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - ./jsoncred.json:/app/jsoncred.json

  agent:
    build:
      context: ./agent
    env_file:
      - .env
    volumes:
      - ./jsoncred.json:/app/jsoncred.json
